apiVersion: v1
kind: Service
metadata:
  name: go-violin-service
  labels:
    app: go-violin-service
spec:
  selector:
    app: go-violin-service
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080