apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-violin-service
  labels:
    app: go-violin-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-violin-service
  template:
    metadata:
      name: go-violin-service
      labels:
        app: go-violin-service
    spec:
      containers:
      - name: go-violin-service-container
        image: 01141354474/online-challenge:latest-1.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "250m"